export const visalist= [
    {
      country: "Canada",
      visa_type: "Express Entry",
      duration: "Permanent Residency",
      processing_time: "6 months",
      application_process: "Points-based system (age, education, work experience, language proficiency)",
      official_link: "https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, through Express Entry or Provincial Nominee Programs (PNPs)"
    },
    {
      country: "Germany",
      visa_type: "EU Blue Card",
      duration: "4 years (can lead to PR)",
      processing_time: "1-3 months",
      application_process: "Job offer with a minimum salary threshold, university degree",
      official_link: "https://www.make-it-in-germany.com/en/visa/eu-blue-card",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 33 months (or 21 months with B1 German)"
    },
    {
      country: "Australia",
      visa_type: "Skilled Independent Visa (subclass 189)",
      duration: "Permanent Residency",
      processing_time: "6-8 months",
      application_process: "Points-based system (age, skills, English proficiency)",
      official_link: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes"
    },
    {
      country: "New Zealand",
      visa_type: "Skilled Migrant Category Resident Visa",
      duration: "Permanent Residency",
      processing_time: "6-12 months",
      application_process: "Points-based system (age, work experience, qualifications)",
      official_link: "https://www.immigration.govt.nz/new-zealand-visas/apply-for-a-visa/about-visa/skilled-migrant-category-resident-visa",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes"
    },
    {
      country: "Portugal",
      visa_type: "D7 Visa",
      duration: "1 year (renewable)",
      processing_time: "2-3 months",
      application_process: "Proof of passive income, accommodation, and health insurance",
      official_link: "https://www.sef.pt/en/pages/d7-visa",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Ireland",
      visa_type: "Critical Skills Employment Permit",
      duration: "2 years (renewable)",
      processing_time: "4-6 weeks",
      application_process: "Job offer in a critical skills occupation, employer sponsorship",
      official_link: "https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/critical-skills-employment-permit/",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Singapore",
      visa_type: "Employment Pass",
      duration: "1-2 years (renewable)",
      processing_time: "3 weeks",
      application_process: "Job offer with a minimum salary, employer sponsorship",
      official_link: "https://www.mom.gov.sg/passes-and-permits/employment-pass",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 2-5 years"
    },
    {
      country: "United Arab Emirates",
      visa_type: "Employment Visa",
      duration: "2-3 years (renewable)",
      processing_time: "2-4 weeks",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.uae.gov.ae/information-and-services/visa-and-emirates-id/work-visa",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "No"
    },
    {
      country: "Japan",
      visa_type: "Highly Skilled Professional Visa",
      duration: "5 years (renewable)",
      processing_time: "1-3 months",
      application_process: "Points-based system (education, work experience, salary)",
      official_link: "https://www.moj.go.jp/isa/applications/procedures/16-4-1.html",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 1-3 years"
    },
    {
      country: "Estonia",
      visa_type: "D-Visa",
      duration: "1 year (renewable)",
      processing_time: "1-2 months",
      application_process: "Proof of employment or business activity in Estonia",
      official_link: "https://www.estonia.ee/visa-and-residence-permit",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Lithuania",
      visa_type: "Work Visa",
      duration: "1 year (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.migracija.lt/en/work-visa",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Italy",
      visa_type: "Work Visa",
      duration: "1-2 years (renewable)",
      processing_time: "1-3 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://vistoperitalia.esteri.it/home/en",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "South Korea",
      visa_type: "E-7 Visa (Special Occupation)",
      duration: "1-3 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer in a specialized field, employer sponsorship",
      official_link: "https://www.hikorea.go.kr/",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Brazil",
      visa_type: "Temporary Work Visa",
      duration: "1-2 years (renewable)",
      processing_time: "1-3 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.gov.br/mre/pt-br/consulado-boston/visas/work-visa",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 4 years"
    },
    {
      country: "Denmark",
      visa_type: "Work Permit",
      duration: "1-2 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.nyidanmark.dk/en-GB/You-want-to-apply/Work",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Botswana",
      visa_type: "Work Permit",
      duration: "1-2 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.gov.bw/visas-and-immigration/work-permit",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Cambodia",
      visa_type: "Work Visa",
      duration: "1 year (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.evisa.gov.kh/",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Netherlands",
      visa_type: "Highly Skilled Migrant Visa",
      duration: "1-5 years (renewable)",
      processing_time: "2-4 weeks",
      application_process: "Job offer with a minimum salary, employer sponsorship",
      official_link: "https://ind.nl/en/work/Pages/Highly-skilled-migrant.aspx",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "France",
      visa_type: "Talent Passport",
      duration: "4 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer in a high-demand field, employer sponsorship",
      official_link: "https://www.france-visas.gouv.fr/en/web/france-visas/talent-passport",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Spain",
      visa_type: "Work and Residence Visa",
      duration: "1-2 years (renewable)",
      processing_time: "1-3 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.exteriores.gob.es/Consulados/LOSANGELES/en/Consular-Information/Pages/Work-and-Residence-Visa.aspx",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Sweden",
      visa_type: "Work Permit",
      duration: "2 years (renewable)",
      processing_time: "1-3 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.migrationsverket.se/English/Private-individuals/Working-in-Sweden.html",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 4 years"
    },
    {
      country: "Norway",
      visa_type: "Skilled Worker Visa",
      duration: "1-3 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.udi.no/en/want-to-apply/work-immigration/",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 3 years"
    },
    {
      country: "Finland",
      visa_type: "Work Permit",
      duration: "1-2 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://migri.fi/en/work-permit",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 4 years"
    },
    {
      country: "Austria",
      visa_type: "Red-White-Red Card",
      duration: "1-2 years (renewable)",
      processing_time: "1-3 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.migration.gv.at/en/working-and-living-in-austria/red-white-red-card/",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Belgium",
      visa_type: "Professional Card",
      duration: "1-2 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://dofi.ibz.be/en/themes/professional-card",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Switzerland",
      visa_type: "Work Permit",
      duration: "1-2 years (renewable)",
      processing_time: "1-3 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.sem.admin.ch/sem/en/home/themen/arbeit.html",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Poland",
      visa_type: "Work Permit",
      duration: "1-2 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.gov.pl/web/udsc/work-permit",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Czech Republic",
      visa_type: "Employee Card",
      duration: "2 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.mvcr.cz/mvcren/article/employee-card.aspx",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    },
    {
      country: "Hungary",
      visa_type: "Work Permit",
      duration: "1-2 years (renewable)",
      processing_time: "1-2 months",
      application_process: "Job offer, employer sponsorship",
      official_link: "https://www.bmbah.hu/index.php?lang=en",
      family_allowed: "Yes",
      financial_proof_required: "Yes",
      permanent_residency_pathway: "Yes, after 5 years"
    }
  ];